module.exports = {
    KeyboardControls: require('./controls/KeyboardControls').default,
    Timer: require('./game/Timer').default,
    MathUtils: require('./lib/MathUtils').default,
    Scheduler: require('./lib/Scheduler').default,
    Trace: require('./lib/Trace').default,
    NetworkedEventCollection: require('./network/NetworkedEventCollection').default,
    NetworkedEventFactory: require('./network/NetworkedEventFactory').default,
    NetworkMonitor: require('./network/NetworkMonitor').default,
    NetworkTransmitter: require('./network/NetworkTransmitter').default,
    BruteCollisionDetection: require('./physics/SimplePhysics/BruteCollisionDetection').default,
    HSHG: require('./physics/SimplePhysics/HSHG').default,
    HSHGCollisionDetection: require('./physics/SimplePhysics/HSHGCollisionDetection'),
    CannonPhysicsEngine: require('./physics/CannonPhysicsEngine').default,
    P2PhysicsEngine: require('./physics/P2PhysicsEngine').default,
    PhysicsEngine: require('./physics/PhysicsEngine').default,
    SimplePhysicsEngine: require('./physics/SimplePhysicsEngine').default,
    PixiRenderableComponent: require('./render/pixi/PixiRenderableComponent').default,
    PixiRenderer: require('./render/pixi/PixiRenderer').default,
    // getter since this relies on THREE global that may not exist at time of lance-gg import
    get AFrameRenderer() {
        return require('./render/AFrameRenderer').default;
    },
    Renderer: require('./render/Renderer').default,
    ThreeRenderer: require('./render/ThreeRenderer').default,
    BaseTypes: require('./serialize/BaseTypes').default,
    DynamicObject: require('./serialize/DynamicObject').default,
    GameComponent: require('./serialize/GameComponent').default,
    GameObject: require('./serialize/GameObject').default,
    PhysicalObject2D: require('./serialize/PhysicalObject2D').default,
    PhysicalObject3D: require('./serialize/PhysicalObject3D').default,
    Quaternion: require('./serialize/Quaternion').default,
    Serializable: require('./serialize/Serializable').default,
    Serializer: require('./serialize/Serializer').default,
    ThreeVector: require('./serialize/ThreeVector').default,
    TwoVector: require('./serialize/TwoVector').default,
    ExtrapolateStrategy: require('./syncStrategies/ExtrapolateStrategy').default,
    FrameSyncStrategy: require('./syncStrategies/FrameSyncStrategy').default,
    InterpolateStrategy: require('./syncStrategies/InterpolateStrategy').default,
    SyncStrategy: require('./syncStrategies/SyncStrategy').default,
    ClientEngine: require('./ClientEngine').default,
    GameEngine: require('./GameEngine').default,
    GameWorld: require('./GameWorld').default,
    ServerEngine: require('./ServerEngine').default,
    Synchronizer: require('./Synchronizer').default,
};
